image: node:13

variables:
  DEPLOY_ENV: 59-shared-shell-x86

stages:
  - deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

deploy:
  tags:
    - $DEPLOY_ENV
  image: docker
  stage: deploy
  script:
    - docker ps
    - docker build -t web-doc .
    - if [ $(docker ps -aq --filter name=web-doc) ]; then docker rm -f web-doc;fi
    - docker run -d -p 4000:4000 --name web-doc web-doc

